name: aura_assistant
description: A powerful AI assistant with voice and text capabilities
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  picovoice: ^1.1.9
  speech_to_text: ^6.3.0
  flutter_tts: ^3.8.3
  dio: ^5.3.2
  web_socket_channel: ^2.4.0
  shared_preferences: ^2.2.1
  json_annotation: ^4.8.1
  google_generative_ai: ^0.4.6
  animated_text_kit: ^4.2.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansSymbols-Regular.ttf